version: "3.8"

name: inception

services:
  nginx:
    container_name: nginx
    image: nginx:42
    build:
      context: ./requirements/nginx
      args:
        - ALPINE_PENULTIMATE_VERSION_TAG=${ALPINE_PENULTIMATE_VERSION_TAG}
    init: true
    depends_on:
      wordpress:
        condition: service_started
    ports:
      - 443:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ${DATA_ROOT}/wordpress:/var/www/html
      - ${DATA_ROOT}/nginx/conf:/etc/nginx/conf.d
      - ${DATA_ROOT}/nginx/cert:/etc/nginx/ssl
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${DATA_ROOT}/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 5s
      interval: 5s
      timeout: 4s
      retries: 10
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - WORDPRESS_DB_HOST=${MARIADB_HOST}
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ${DATA_ROOT}/wordpress:/var/www/html
    restart: unless-stopped

networks:
  default:
    name: inception-net
