CREATE DATABASE IF NOT EXISTS <DATABASE>;
CREATE USER IF NOT EXISTS '<USER>'@'%';
SET PASSWORD FOR '<USER>'@'%' = PASSWORD('<PASSWORD>');
GRANT ALL PRIVILEGES ON <DATABASE>.* TO '<USER>'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '<ROOT_PASSWORD>';
FLUSH PRIVILEGES;

